name: Create Release
on:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read
jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v-${{ github.run_number }}",
              sha: context.sha
            })

  create-release:
    needs: create-tag
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions: write-all
    steps:  
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v-${{ github.run_number }}
          release_name: Release-${{ github.run_number }}
